apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: nodeapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp 
    spec:
      containers:
      - name: nodeapp
        image: localhost:5001/nodeapp:latest
        env:
        - name: NODE_ENV
          value: "development"
        - name: APP_PORT
          value: 3000
        - name: APP_NAME
          value: "server1"
        - name: APP_TARGET_HOST
          value: "server2"
        - name: APP_TARGET_PORT
          value: 3001
        ports:
        - containerPort: 3000